// Generated by CoffeeScript 1.7.1

/*
Whack-A-Mole
Freely reused from the Cocos2d Whack-a-mole Tutorial
http://maniacdev.com/2011/01/tutorial-cocos2d-example-whack-a-mole-game/
Original version by Ray Wenderlich, the creator of the Space Game Starter
Kit and co-author of the Learning Cocos2D book, as part of an excellent set
of iOS tutorials on how to create a whack-a-mole game using the open source
iPhone game engine Cocos2D.
 */
var game;

game = {

  /*
  local game data
   */
  data: {
    score: 0,
    hiscore: 0
  },

  /*
  some Initialization
   */
  onload: function() {
    me.sys.fps = 30;
    if (!me.video.init("screen", 1024, 768, true, "auto")) {
      alert("Sorry but your browser does not support html5 canvas. Please try with another one!");
      return;
    }
    if (document.location.hash === "#debug") {
      window.onReady(function() {
        me.plugin.register.defer(debugPanel, "debug");
      });
    }
    me.audio.init("mp3,ogg");
    me.save.add({
      hiscore: 0
    });
    game.data.hiscore = me.save.hiscore;
    me.loader.onload = this.loaded.bind(this);
    me.loader.preload(game.resources);
    me.state.change(me.state.LOADING);
  },

  /*
  callback when everything is loaded
   */
  loaded: function() {
    me.state.set(me.state.PLAY, new game.PlayScreen());
    me.state.transition("fade", "#000000", 250);
    me.state.change(me.state.PLAY);
  }
};
