// Generated by CoffeeScript 1.7.1

/*
Whack-A-Mole
Freely reused from the Cocos2d Whack-a-mole Tutorial
http://maniacdev.com/2011/01/tutorial-cocos2d-example-whack-a-mole-game/
Original version by Ray Wenderlich, the creator of the Space Game Starter
Kit and co-author of the Learning Cocos2D book, as part of an excellent set
of iOS tutorials on how to create a whack-a-mole game using the open source
iPhone game engine Cocos2D.
 */
game.resources = [
  {
    name: "background",
    type: "image",
    src: "data/img/background/bg_dirt128.png"
  }, {
    name: "grass_upper",
    type: "image",
    src: "data/img/foreground/grass_upper128.png"
  }, {
    name: "grass_lower",
    type: "image",
    src: "data/img/foreground/grass_lower128.png"
  }, {
    name: "mole",
    type: "image",
    src: "data/img/sprites/mole.png"
  }, {
    name: "atascii",
    type: "image",
    src: "data/img/sprites/atascii_24px.png"
  }, {
    name: "whack",
    type: "audio",
    src: "data/bgm/"
  }, {
    name: "ow",
    type: "audio",
    src: "data/sfx/",
    channel: 2
  }
];
